version: "3"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:inception
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./.env
    expose:
      - 3306
    networks:
      - my
    restart: always

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:inception
    volumes:
      - wp:/var/www/html/wordpress
    env_file:
      - ./.env
    expose:
      - 9000
    networks:
      - my
    restart: always

  nginx:
    depends_on:
      - mariadb
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:inception
    volumes:
      - wp:/var/www/html/wordpress
    env_file:
      - ./.env
    ports:
      - 443:443
    networks:
      - my
    restart: always

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: '/home/kwsong/data/db'
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: '/home/kwsong/data/wp'
      o: bind

networks:
  my: 
    driver: bridge