CREATE DATABASE $(WORDPRESS_DB_NAME);
CREATE USER $(WORDPRESS_DB_USER)@$(WORDPRESS_DB_HOST) IDENTIFIED BY $(WORDPRESS_DB_PASSWORD);
GRANT ALL ON wordpress.* TO $(WORDPRESS_DB_USER)@$(WORDPRESS_DB_HOST) ;
FLUSH PRIVILEGES;
exit
